### ISSUE TITLE
[FEATURE]:Add  Some New Quote

### ISSUE THREAD

**Issue by Skb08** [Shariar-Hasan/QuoteVerse#1]
Hi, I want to add some more quotes under hacktoberfast.
Can you assign me this with hacktoberfast level.

**Comment by Thanush19** [comment]
kindly review my PR @Shariar-Hasan

**Comment by rohits-web03** [comment]
#### Since this issue is not assigned to anyone.Can you assign me this issue?
#### I can add some more quotes to Quotes.js file

**Comment by Shariar-Hasan** [comment]
✅🆗

**Comment by om453** [comment]
hello can you also assign me this issue i want to add some more quotes in this repo

**Comment by Shariar-Hasan** [comment]
🆗assigned

**Comment by mtahashahid** [comment]
Hi, I want to add some quotes
Can you assign me under hacktoberfest?

**Comment by Shariar-Hasan** [comment]
🆗assigned

**Comment by rohits-web03** [comment]
#### I have made the necessary changes and opened a pull request #15 .Can you check and merge it?

**Comment by Shariar-Hasan** [comment]
> #### I have made the necessary changes and opened a pull request #15 .Can you check and merge it?

check comment in your pull request

**Comment by Oblivious19** [comment]
Can i contribute into adding some quotes?

**Comment by Shariar-Hasan** [comment]
sure, give a start in the repo ⭐
fork the repo ✅
contribute & create PR

**Comment by Kapileswar-Moharana** [comment]
Assign this issue to me under Hacktoberfest, I will Add some of the quotes. Assign this issue to me.

**Comment by Shariar-Hasan** [comment]
sure,
assigned to you. but make sure to read the [rules ](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)first

**Comment by Kapileswar-Moharana** [comment]
> ad the [rules ](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)first

okay
