### ISSUE TITLE
[BUG]: Cant-See-Share-Options

### ISSUE THREAD

**Issue by KiranPolaki** [Shariar-Hasan/QuoteVerse#100]
I want to bring up this issue as i cant' see the  share options on color change. this will be fixed in two ways

1)Using neutral colors.
2)Using a background color for that share-button's box.

### Screenshot of the issue.

![image_2023-10-22_002314679](https://github.com/Shariar-Hasan/QuoteVerse/assets/121670156/c02c600f-7b9a-4820-93a4-b33209628a59)

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] i am sure, this issue is not raised before.

### Do you want to fix the issue?

Yes, I want to fix it

**Comment by Shariar-Hasan** [comment]
option 2 would be better, as logos main element has fixed color.
assigned

**Comment by KiranPolaki** [comment]
![image_2023-10-22_005309541](https://github.com/Shariar-Hasan/QuoteVerse/assets/121670156/82fb66e4-5f54-4748-82b8-ee3174ed99b6)

Do let me know if this is ok?

**Comment by Shariar-Hasan** [comment]
a more darker would be better

**Comment by KiranPolaki** [comment]
Done I will be on it.

**Comment by KiranPolaki** [comment]
![image_2023-10-22_112125497](https://github.com/Shariar-Hasan/QuoteVerse/assets/121670156/e6e9150f-d4fc-4384-ab72-b6d57cbcabe1)

Can i proceed with this?

**Comment by Shariar-Hasan** [comment]
make a pr
