### ISSUE TITLE
[BUG] Missing Favicon 

### ISSUE THREAD

**Issue by pratap360** [Shariar-Hasan/QuoteVerse#112]
### Description

- Just wanted to add the missing favicon in the site 
- check the screenshot below

### Screenshots

![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/52885495/d8ccbf4a-1e94-4ba2-9d9d-e6190935b68b)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

### Are you willing to work on this issue ?

_Yes I already submit a PR! on this , do check #111_

**Comment by Kapileswar-Moharana** [comment]
@pratap360 Can I do this issue Under Hacktoberfest

**Comment by Shariar-Hasan** [comment]
@pratap360 
your pull request has been cancel,
[reason is here ](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

**Comment by Kapileswar-Moharana** [comment]
@Shariar-Hasan hey can I contribute on this issue under Hacktoberfest

**Comment by Shariar-Hasan** [comment]
@Kapileswar-Moharana ,
if @pratap360  still want to contribute,
then he is assigned.
as he created the issue,
if not,
wait for one day,
then you can get assigned.
else you can find or create another issue to add feature or bug fix.
must read [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

**Comment by pratap360** [comment]
Please assign it to me I still wanted to contribute to this issue 😅 but what mistakes I have made ? 🤔 @Shariar-Hasan you close the PR 😅 Any serious issue 👀 ?

**Comment by Shariar-Hasan** [comment]
every issue is serious, as a project proffessinally you have to check out dozens of conflict,
rules are rules.
 you broke the main rule
- made a PR without getting assigned
- made PR with adding quotes along with a favicon feature.(but your created issue says only favicon issue, do what you are assigned for)
- and lastly you didnt starred the repo(which you just did 30 mintue ago.)

**Comment by Shariar-Hasan** [comment]
now you are assigned.
for QuoteVerse,
try to make favicon with "QV"

**Comment by pratap360** [comment]
Thanks for  Merge my PR
