### ISSUE TITLE
[OTHER] Add quotes for the art category

### ISSUE THREAD

**Issue by kaur-rajdeep** [Shariar-Hasan/QuoteVerse#113]
### Description

 
I just looked for quotes under the Art category and found that it's just single quote. I would like to add some quotes under this category.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by WilsonZ-CS** [comment]
Can I be assigned to this please? Thank you!

**Comment by Shariar-Hasan** [comment]
You dont have to create an issue or get assigned to add quote,
just star the repo and make a PR
