### ISSUE TITLE
[BUG]: Once a background color is selected, there is no way to go back to the white bg color except when we refresh the page. 

### ISSUE THREAD

**Issue by abhayvershwal** [Shariar-Hasan/QuoteVerse#117]
### Kindly explain, what is the issue or what bug do you want to be fixed?

I want to add an option to go back to the white background color that appears at the start of the page. 

### Screenshot of the issue.

![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/93792490/7956cbc1-ab67-498c-aa87-28d5eae76234)

### What browsers are you seeing the problem on?

Google Chrome

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] i am sure, this issue is not raised before.

### Do you want to fix the issue?

Yes, I want to fix it

**Comment by Shariar-Hasan** [comment]
fix it means?
do you want to add another button of color with the other 4 button ?
or anything else?
can you elaborate more about this?

**Comment by abhayvershwal** [comment]
I would like to add white to the list with the other 4 colors. How does that sound?

> and one more thing, main color is not white color. careful about it

Can you please explain this? It is the first color coming up on refresh that is why I assumed so.

**Comment by Shariar-Hasan** [comment]
> Can you please explain this? It is the first color coming up on refresh that is why I assumed so.

i meant, it is not fully white.


> I would like to add white to the list with the other 4 colors. How does that sound?

not bad, do it, no problem , you are assigned
