### ISSUE TITLE
[OTHER] Enhance Share with button

### ISSUE THREAD

**Issue by Virtual4087** [Shariar-Hasan/QuoteVerse#118]
### Description

The "share with" option doesn't look very good. I would love to improve it's styling.

### Screenshots

![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/119912892/311fa1a0-cd8c-447f-a9a8-6b3c6e5bb6c7)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Shariar-Hasan** [comment]
can you give me any screen shot or any short description of, what you want to do?

**Comment by Virtual4087** [comment]
I would like add some padding also fix the hover effect on copy button. Right now when you hover over copy button, it affects it's surrounding as well. I would like to either fix the hover effect or remove it. I Think removing it would look better as it would then match with other social media buttons.

**Comment by IbraheemHaseeb7** [comment]
hi @Virtual4087 I have submitted PR for this issue...let me know if any changes are needed.

**Comment by Shariar-Hasan** [comment]
> hi @Shariar-Hasan I have submitted PR for this issue...let me know if any changes are needed.

@IbraheemHaseeb7 
are you assinged for this issue?
if no, then why did you created a PR?



> I would like add some padding also fix the hover effect on copy button. Right now when you hover over copy button, it affects it's surrounding as well. I would like to either fix the hover effect or remove it. I Think removing it would look better as it would then match with other social media buttons.

@Virtual4087 
okay, i got the idea,
you are assinged. go for it 💥

**Comment by Virtual4087** [comment]
@Shariar-Hasan I'm on it.
