### ISSUE TITLE
[FEATURE]: Add toaster for better user interaction

### ISSUE THREAD

**Issue by MurtazaShikari** [Shariar-Hasan/QuoteVerse#120]
### Description

I would like to suggest of adding a toaster when a new quote is generated have implemented it and have attached the video how it will look on the website if any changes needed do tell me

### Screenshots.

Video below shows how the page responds when we generate a new quote

https://github.com/Shariar-Hasan/QuoteVerse/assets/114511800/9ea4cb57-9ebc-4b2d-a6fb-baa977a1bb11

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] I checked and didn't find similar issue

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Shariar-Hasan** [comment]
i dont think it will look good as everytime you click i generates a toaster.

**Comment by Shariar-Hasan** [comment]
If You want it for hacktober fest, then you can add quotes.
but first read the contribution guideline must.
