### ISSUE TITLE
Change the Twitter logo to X logo

### ISSUE THREAD

**Issue by IbraheemHaseeb7** [Shariar-Hasan/QuoteVerse#127]
### Description

The share button still has Twitter's old logo on it which is obviously outdated. Kindly assign me and I can update it to the new logo.

### Screenshots

![image](https://user-images.githubusercontent.com/119912892/277299354-311fa1a0-cd8c-447f-a9a8-6b3c6e5bb6c7.png)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by supunvindula** [comment]
Hi there! I'm interested in working on this issue. Could you please assign it to me? I believe I can make a valuable contribution to this task.

Looking forward to your response. Thanks!

**Comment by Shariar-Hasan** [comment]
@IbraheemHaseeb7 
yeah, this could  be a good issue,
go for it, you are assigned.

@supunvindula  
if you find any bug or, want to add any feature,
create an issue,
this issue is assigned to the issue creator.
