### ISSUE TITLE
[FEATURE] Share button for twitter

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/QuoteVerse#13]
Create an interactive share to Twitter button.
don't forget to add up the quote with it, so that the quote with author name, can be share to Twitter.

**Comment by Oblivious19** [comment]
i would like to try this issue... have already started would help if you assign it

**Comment by Shariar-Hasan** [comment]
sure why not, just follow the given criteria:
- start the repository 
- fork the repo
- do whatever change you want
- take a screenshot of your change in UI & attach it with your PR

happy hacktober ⭐

**Comment by Shariar-Hasan** [comment]
Dear @Oblivious19 ,
are you working on it?

**Comment by Oblivious19** [comment]
Yes... Will try completing soon

**Comment by Shariar-Hasan** [comment]
when ever you do, 
first of all, make your git repository sync with the original repository,
then make a git pull,
as many UI changes has happend in  the original repository.
else, your commit will get conflict, will not get merged.

**Comment by Shariar-Hasan** [comment]
kindly check the [milestone for 48 hours](https://github.com/Shariar-Hasan/QuoteVerse/milestone/1) to finish the work.
else we have to unassign you 🙂

**Comment by adit-shriyans** [comment]
Hey @Oblivious19, @Shariar-Hasan if it is fine with both of you can you assign this issue to me

**Comment by Shariar-Hasan** [comment]
> Hey @Oblivious19, @Shariar-Hasan if it is fine with both of you can you assign this issue to me

Go for it, You are assigned.
