### ISSUE TITLE
[FEATURE]: <To Add Heading to the Application (QuoteVerse)>

### ISSUE THREAD

**Issue by harshkas4na** [Shariar-Hasan/QuoteVerse#134]
### Description

Nothing big , I observe that there is no name or heading of the platform on the software

### Screenshots.

![Screenshot 2023-10-24 005225](https://github.com/Shariar-Hasan/QuoteVerse/assets/122095220/bd75846d-61f8-433b-8a04-7b26b55a16fc)

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] I checked and didn't find similar issue

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by harshkas4na** [comment]
@Shariar-Hasan  Can you confirm me is this feature reqired or not? and can i work on this?

**Comment by Shariar-Hasan** [comment]
for now, there is no need for it.
but if you want to contribute,
you can read the contribution guideline and fix bug, add any other feature, or add quotes.

**Comment by harshkas4na** [comment]
@Shariar-Hasan ,ok thanks man to confirm ,I will try to another contribution
