### ISSUE TITLE
[Enhancement] : improve the UI

### ISSUE THREAD

**Issue by Hardik2972** [Shariar-Hasan/QuoteVerse#139]
### Description

I want to Improve the UI of the buttons section 
can you please assign it to me ?

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Shariar-Hasan** [comment]
according to contribution guiddeline, you have to star the repo befor emaking a PR
