### ISSUE TITLE
Add and show contributor list

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/QuoteVerse#14]
Show contributor list as aligned center below the container box.
if you have better idea to show them,
do it , we will review.

**Comment by rohits-web03** [comment]
#### I would like to work on this.
#### I am thinking of adding a button at the bottom of the container named "Contributors" which opens another page which shows the list of contributors.What do you think?
#### I would really appreciate it if you assign me this issue.

**Comment by Shariar-Hasan** [comment]
got fo rit brother 🔥

**Comment by rohits-web03** [comment]
#### I have made the necessary changes and open a pull request(#20) for this.
