### ISSUE TITLE
[Improvement] <Expanding the Quotes Database>

### ISSUE THREAD

**Issue by HartzFrequency** [Shariar-Hasan/QuoteVerse#146]
### Description

hey @Shariar-Hasan 
I want to expand the database of quotes 
Adding more quotes in each categories 
This will help the Program to generate more random quotes 
Thank you

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by HartzFrequency** [comment]
Please assign it to me

**Comment by Shariar-Hasan** [comment]
you can add quote,
Adding quote dont need to be assigned.
So just add quotes,
Make PR.


Dont forget to star the repo, as it is a contribution criteria.
