### ISSUE TITLE
[BUG] Duplication In Quotes.js

### ISSUE THREAD

**Issue by HartzFrequency** [Shariar-Hasan/QuoteVerse#150]
### Description

hey @Shariar-Hasan 
While I was scrolling through the Quotes.js file, I found duplicate quotes uploaded by a lot of users. I can clean up the Quotes.js for the project so that there is a single instance of each quote.
Thank you!

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Shariar-Hasan** [comment]
yes of course,
fir duplicate quotes, keep the first one and delete others.
thanks for noticing.
