### ISSUE TITLE
[Improvement] <Home Screen UI Can be improved>

### ISSUE THREAD

**Issue by himangshumishra** [Shariar-Hasan/QuoteVerse#151]
### Description

Hello sir, If you will assign me this task then I can redesign the home UI.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Shariar-Hasan** [comment]
how would it be like?
can you give me any ide about it?
or any demo?

**Comment by dipayansarkar47** [comment]
Hello sir, I can work on this. Please assign it to me

**Comment by himangshumishra** [comment]
> how would it be like? can you give me any ide about it? or any demo?

Ok, I am giving the demo today.

**Comment by himangshumishra** [comment]
> how would it be like? can you give me any ide about it? or any demo?

![Quote-generator-design](https://github.com/Shariar-Hasan/QuoteVerse/assets/115614942/17f99110-033a-4b6d-b276-7335655ecad7)
How is the design?

**Comment by Shariar-Hasan** [comment]
are you willing to keep the styling same, but move the positions?

or like your first image design?

**Comment by himangshumishra** [comment]
> @himangshumishra
> 
> ok i am openning a new branch for you, "New Look"
> 
> create a PR, and merge in that branch.

Ok I am working on that and it will take some time to complete.

**Comment by Shariar-Hasan** [comment]
@himangshumishra 
are you working on it?

**Comment by himangshumishra** [comment]
> @himangshumishra are you working on it?

I was working but due to some timing issues, it was not completed. His design is nice. He did it better.

**Comment by himangshumishra** [comment]
Yes 
This is : https://github.com/Shariar-Hasan/QuoteVerse/pull/175
