### ISSUE TITLE
[BUG]: Config to control code formatting

### ISSUE THREAD

**Issue by therahulchaurasia** [Shariar-Hasan/QuoteVerse#160]
### Kindly explain, what is the issue or what bug do you want to be fixed?

Can I add a prettier config file to the project?
While I was working on adding a feature in this project I saw that my code formatter changed the entire file's formatting when adding a few quotes at the bottom of the file. The formatting methods used by other people depend on their requirements. Since, many people are contributing to this project it would be handy to have a prettier config file so that the editor can pick up the local configuration and work accordingly. 

### Screenshot of the issue.

You can see that some of the code contains quoted("") objects while most of the code doesn't.
![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/90378272/db239007-2b63-4472-94d1-cb18300d4ff6)
Whereas adding a prettier config makes the code more maintainable
![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/90378272/dda5e904-4d36-4643-b528-7ffba8275c32)

### What browsers are you seeing the problem on?

Google Chrome

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [x] i am sure, this issue is not raised before.

### Do you want to fix the issue?

Yes, I want to fix it

**Comment by therahulchaurasia** [comment]
Please assign this issue to me.

**Comment by Shariar-Hasan** [comment]
i have thought about it, as most of the user who will contribute in this repository, are the begineer, thats why i thought they wont understand much about linting.
as it is not a higer level or production level project, thats why i didnt added any linter as long as there is any kind of error.

**Comment by therahulchaurasia** [comment]
Well, you are right on point. We don't need linters because they would be too much for any beginner. 
But, I would like to add a prettier config so that the code get's formatted in a similar way for anyone that hits the save button.
I think it would make easier for you as well when you view the pull request.

**Comment by Shariar-Hasan** [comment]
well in that case, you are assigned.
feel free to contribute & feel free to star the repo if you want 😀😀

**Comment by therahulchaurasia** [comment]
Thanks a lot. I'll submit a PR after all the testing is done on my end.
