### ISSUE TITLE
[BUG]: Fix Generate Button Functionality

### ISSUE THREAD

**Issue by purnasth** [Shariar-Hasan/QuoteVerse#161]
### Kindly explain, what is the issue or what bug do you want to be fixed?

In the QuoteVerse collection, the 'Generate' button is currently non-functional. When clicking on the 'Generate' button, the quotes are not being generated as intended. I propose to resolve this issue by fixing the functionality of the 'Generate' button to display quotes effectively.

### Screenshot of the issue.

https://github.com/Shariar-Hasan/QuoteVerse/assets/107195487/2e0939f7-31e0-4fd4-83fe-1cfd75c428ad

![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/107195487/6d08cb1b-2e75-48d5-9254-af1584fd784a)

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] i am sure, this issue is not raised before.

### Do you want to fix the issue?

Yes, I want to fix it

**Comment by Shariar-Hasan** [comment]
didnt noticed, when did it happened.
yeah, fix it
