### ISSUE TITLE
[BUG]: Contributors Page doesn't show all contributors

### ISSUE THREAD

**Issue by IbraheemHaseeb7** [Shariar-Hasan/QuoteVerse#165]
### Kindly explain, what is the issue or what bug do you want to be fixed?

I want to add perhaps pagination to the contributor's page and show all of the contributors of the repo.

### Screenshot of the issue.

![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/81369271/2d57cc33-f22b-45af-a68a-4e188cf55ceb)

### What browsers are you seeing the problem on?

Google Chrome

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] i am sure, this issue is not raised before.

### Do you want to fix the issue?

Yes, I want to fix it

**Comment by Shariar-Hasan** [comment]
in this case. you have to  maintain the number of contributor in one page, for mobile, desktop with out the overflow scroll.
assigned
