### ISSUE TITLE
[BUG]: Logo not appearing on the Contributor Page's Tab

### ISSUE THREAD

**Issue by IbraheemHaseeb7** [Shariar-Hasan/QuoteVerse#168]
### Kindly explain, what is the issue or what bug do you want to be fixed?

You can not see the quote verse logo on the tab of the contributor's page. I will fix it.

### Screenshot of the issue.

![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/81369271/d0211297-b490-433d-abc9-929cfd84c968)

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] i am sure, this issue is not raised before.

### Do you want to fix the issue?

Yes, I want to fix it

**Comment by Shariar-Hasan** [comment]
oh, thats a bug,
fix it,
thanks for wanting to contribute

**Comment by amanjaiman1** [comment]
@IbraheemHaseeb7 Should i work on UI , please tell me

**Comment by Shariar-Hasan** [comment]
> @IbraheemHaseeb7 Should i work on UI , please tell me

what kind of work,
can you elaborate  more?
