### ISSUE TITLE
[FEATURE]: Share with button should be clickable and create a popup ui

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/QuoteVerse#176]
### Description

![image](https://github.com/user-attachments/assets/80ccbe98-8e7f-4c6e-98aa-9caf31d9c5f6)
this share button should create a popup ui with different sharable links

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] I checked and didn't find similar issue

### Are you willing to work on this issue ?

None

**Comment by theCodeCrusaderX** [comment]
please assign this task to me!!

**Comment by Vishrut99** [comment]
please assign this task to me

**Comment by Shariar-Hasan** [comment]
@theCodeCrusaderX  you are assigned, kindly show a output image or video or gif for better view.
thanks.

**Comment by Shariar-Hasan** [comment]
@Vishrut99 as other person asked for the assignment before you and it has first come first serve procedure. Don't mind.
the website has many bugs, you can contribute on them, or you can apply a new feature for the site.
please do read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md). That will help you how to contribute on the project.
thanks for the approach.
😉
