### ISSUE TITLE
[FEATURE]: adding quotes for growth category 

### ISSUE THREAD

**Issue by Karnmayank07** [Shariar-Hasan/QuoteVerse#180]
### Description

I just looked for quotes under the growth  category and found that it's just single quote. I would like to add some quotes under this category.

add hactoberfest-accepted label and assign me 

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] I checked and didn't find similar issue

### Are you willing to work on this issue ?

None

**Comment by theCodeCrusaderX** [comment]
Please assign this task to me !!
