### ISSUE TITLE
[FEATURE]: Like Functionality

### ISSUE THREAD

**Issue by papireddy903** [Shariar-Hasan/QuoteVerse#183]
### Description

Implement a "Like" functionality for quotes. Users should be able to like a quote, and the "like" status should persist using localStorage. By default, all quotes should be unliked. Once a quote is liked, it should be visually marked, and that state should remain even after refreshing or navigating the page. 

### Screenshots.

![image](https://github.com/user-attachments/assets/8e9e4447-a3c2-4a2e-b56c-af0b33fdc738)

### Additional information

The feature would help improve user engagement and allow users to track which quotes they have liked.

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] I checked and didn't find similar issue

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Shariar-Hasan** [comment]
that would be great.
go on
