### ISSUE TITLE
[FEATURE]: Multilingual Support

### ISSUE THREAD

**Issue by saumy-sh** [Shariar-Hasan/QuoteVerse#185]
### Description

Multilingual Support is an important feature for web applications aiming to cater to a global audience. Adding this capability to a project like Quoteverse enhances accessibility and usability for users who speak different languages, making it a more inclusive platform.
Here is what things this feature will include and steps of implementing it:
 - i18n Library: We'll use an internationalization (i18n) library such as react-i18next to manage language switching dynamically in the app.
 - Language Files: Create separate JSON files for each supported language (e.g., en.json, es.json) containing translated text for UI elements.
 - Language Toggle: A simple toggle button or dropdown will allow users to switch between languages seamlessly.

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] I checked and didn't find similar issue

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by saumy-sh** [comment]
I would very much like to work on this issue. Can you assign it to me?

**Comment by saumy-sh** [comment]
Hey any update on this? Should I start working on it.

**Comment by Shariar-Hasan** [comment]
yeah sure, go on.
you are assigned.

**Comment by BaniSinghgithub** [comment]
hello sir @Shariar-Hasan ,  can you pls assign this work to me.

**Comment by Shariar-Hasan** [comment]
hello, @BaniSinghgithub 
this issue is already assigned to another person.
you can find any other bug on the site, or you can add quote or any other feature.
best  of luck

**Comment by saumy-sh** [comment]
hey @Shariar-Hasan , I would like to discuss with you two approaches, one is using manual translations stored as json file for each quote in different languages and other is to use API(like google translator). 
First one is free but of course, people doing new contributions in quotes will have to add quote in all different languages. For already existing quotes I can add translations in different languages. 
The other approach is much simpler, Google will be able to all work, but you will have to setup an account and generate your API key. It will only after 500,000 characters have been used per month.
Which approach should I take?

**Comment by Shariar-Hasan** [comment]
The first one would be better i guess.
do your best.
best of luck

**Comment by Shariar-Hasan** [comment]
i thought i would do that,
but it would be more great if you do it.
thank you very much ✌️✌️

**Comment by saumy-sh** [comment]
sure I am working on it!

**Comment by saumy-sh** [comment]
I have added multilingual and it's working(video attached).

https://github.com/user-attachments/assets/d5cc3f78-fdd0-4907-b342-00214e7a379d

But there are so many quotes and adding translations to each is cumbersome, so I have added translations for one of the quote to show the feature. Can I make PR with this and adding translations part can be left for other contributors to contribute to?

**Comment by saumy-sh** [comment]
going ahead with these changes, I have opened a PR.
