### ISSUE TITLE
Todo app with a table

### ISSUE THREAD

**Issue by BaniSinghgithub** [Shariar-Hasan/QuoteVerse#189]
### Description

making a todo app collecting data in a form and showing the data in the form of a table.
the table, will be adjacent to form, storing the data from table.

### Screenshots

![image](https://github.com/user-attachments/assets/e6d2c139-9515-4210-90cc-5930d56a05ec)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by BaniSinghgithub** [comment]
hello sir @Shariar-Hasan , can you pls assign this work to me.

**Comment by Shariar-Hasan** [comment]
hello @BaniSinghgithub 
i actually dont understand what are you trying to say,
maybe you mistakenly created an issue in different repository

**Comment by BaniSinghgithub** [comment]
hello @Shariar-Hasan , I am trying to make an app, that will store form data in a table, right side of the form

**Comment by Shariar-Hasan** [comment]
thats great, but this app, where you are commenting now, not  currently considered  for any other thought other than generating quotes.
best of luck.

**Comment by Shariar-Hasan** [comment]
closing this issue now.
