### ISSUE TITLE
[FEATURE]: Add WhatsApp share button for QuoteVerse

### ISSUE THREAD

**Issue by rohits-web03** [Shariar-Hasan/QuoteVerse#21]
#### Would really appreciate it if you assign me this issue under Hacktoberfest 2023.

**Comment by Shariar-Hasan** [comment]
sure why not, just follow:
- star the repo,
- make a clone of the repo
- do neccessary changes
- make a PR

**Comment by Kapileswar-Moharana** [comment]
Assign this issue to me under Hcktoberfest, As I already worked on these issues. So assign this to me.

**Comment by Shariar-Hasan** [comment]
> Assign this issue to me under Hcktoberfest, As I already worked on these issues. So assign this to me.
dear @Kapileswar-Moharana ,
as it is already assigned to someone, you can contribute on other issues or add a new issue with feature adding or bug fixing.
but first of all read the [rules first](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md) 

if the assigned person doesnt get his job done with in 48 hours,
we will ask you to do so .
happy hacktoberfest 🥳

**Comment by Kapileswar-Moharana** [comment]
> > Assign this issue to me under Hcktoberfest, As I already worked on these issues. So assign this to me.
> > dear @Kapileswar-Moharana ,
> > as it is already assigned to someone, you can contribute on other issues or add a new issue with feature adding or bug fixing.
> > but first of all read the [rules first](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
> 
> if the assigned person doesnt get his job done with in 48 hours, we will ask you to do so . happy hacktoberfest 🥳

Okay Then

**Comment by rohits-web03** [comment]
#### Kindly check #28  and merge it
