### ISSUE TITLE
[FEATURE]: Contributor list should be clickable

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/QuoteVerse#24]
![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/75330767/c417dadc-27ec-4d95-9d55-3be385270719)
this are not clickable.
your work is to make them clickable in such way that, when any user click on any of the contributor,
it will take the user to that contributors profile.

but make sure to start the repository and [read the rules](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

**Comment by IrfanSalim** [comment]
Hey, I would like to work on this. Please assign

**Comment by Shariar-Hasan** [comment]
sure, 
make sure to [read the rules ](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

**Comment by CertificationSurya** [comment]
hey assign me, I wanna work.

**Comment by Shariar-Hasan** [comment]
> hey assign me, I wanna work.

dear @CertificationSurya 
one person is already assigned.
you can check for other issues.

**Comment by IrfanSalim** [comment]
Hey, @Shariar-Hasan 

I think we can achieve this using GitHub workflows, is that fine?

**Comment by Shariar-Hasan** [comment]
> Hey, @Shariar-Hasan
> 
> I think we can achieve this using GitHub workflows, is that fine?

Can you please elaborate more?
i think, you can do it by using an anchor tag,
and links are already generated in the api.

**Comment by IrfanSalim** [comment]
My bad, I thought you wanted to update the list in your readme.

Ignore the previous comment please

**Comment by IrfanSalim** [comment]
![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/109443065/ead239aa-0fb7-4b5b-bebc-e675cbd18c79)

changed the styling to look uniform, is this fine?

**Comment by IrfanSalim** [comment]
@Shariar-Hasan

**Comment by Shariar-Hasan** [comment]
> ![image](https://user-images.githubusercontent.com/109443065/275574913-ead239aa-0fb7-4b5b-bebc-e675cbd18c79.png)
> 
> changed the styling to look uniform, is this fine?

looks good, it would be more beautiful if you make all the card of same size.
than make a pull request mentioning this issue.

**Comment by Shariar-Hasan** [comment]
ok wait a bit,
some conflict happened in other PR.
