### ISSUE TITLE
[BUG]:  the background resizes according to the length of the quote 

### ISSUE THREAD

**Issue by lokesh932338** [Shariar-Hasan/QuoteVerse#39]
### Screenshot:🔴mandatory 
<img width="958" alt="Screenshot 2023-10-17 235451" src="https://github.com/Shariar-Hasan/QuoteVerse/assets/142098970/37b2bfcb-8c4c-4e8a-8428-cf240ddcef94">

<img width="957" alt="Screenshot 2023-10-17 235517" src="https://github.com/Shariar-Hasan/QuoteVerse/assets/142098970/0a8e989e-bf72-4fcc-8e36-65e8343908d8">

### Conditions check:

- [x] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md#rules-for-fixing-bugs)

- [x] i am sure, this issue is not raised before.

- [x] i will try to do fix the bug properly.

**Comment by lokesh932338** [comment]
please assign me this issue

**Comment by Shariar-Hasan** [comment]
![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/75330767/2cc06c5c-3df5-4eb4-bb51-33984a932893)
false tic,
this issue you arrised, alreday been solved by someone just now.
you can work other bug, or add quotes

**Comment by lokesh932338** [comment]
i didnot found where this bug is solved, and i cloned the latest code
