### ISSUE TITLE
[BUG] color of theme changer button are not related to their behavior

### ISSUE THREAD

**Issue by lokesh932338** [Shariar-Hasan/QuoteVerse#42]
the theme changer radio buttons are intended to change the background color of container element but their displayed color and the color they change are different.

### Screenshot:🔴mandatory 
<img width="957" alt="Screenshot 2023-10-18 004554" src="https://github.com/Shariar-Hasan/QuoteVerse/assets/142098970/8aa1ed7e-1cf0-46ab-8fe2-c90f010c65e9">

### Conditions check:

- [x] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md#rules-for-fixing-bugs)

- [x] i am sure, this issue is not raised before.

- [x] i will try to do fix the bug properly.

**Comment by lokesh932338** [comment]
please assign this issue after confirming the issue

**Comment by Shariar-Hasan** [comment]
great finding.
it is a bug.
ok i am assigning this to you,

you must star the repository,
make the changes and make a PR.
get sync with the repository before making PR,
else you will get a conflict
