### ISSUE TITLE
[FEATURE]: Copy to Clipboard button

### ISSUE THREAD

**Issue by Jenish-Dhanani** [Shariar-Hasan/QuoteVerse#50]
### Description

The UX of the QuoteVerse will be improved if we add a copy to clipboard button (small icon) to directly copy the quote.

There is another option too: Instead of adding a button, the text will be copied to the clipboard automatically if the user clicks within the Quote.

Let me know which is the best option and if any further details are required! 

Thanks,
Jenish

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] I checked and didn't find similar issue

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Shariar-Hasan** [comment]
You can do the button thing, i guess
but the controller section section will too much messy,



i am giving you the opportunity to do any of those 2 option.
but try to make it look good

**Comment by Jenish-Dhanani** [comment]
@Shariar-Hasan  Thanks, I will implement both and I will add a button in the social share container.

**Comment by Shariar-Hasan** [comment]
go for it.
after pull request, you have resolve issues if there any.
else the branch will not get merged.
dont forget to star the repo.
react the contribution rules

**Comment by Shariar-Hasan** [comment]
hello @Jenish-Dhanani ,
just a clarifiation,
you have to copy both quote and author.
for exmaple : "<copied-quote> - <copied-author-name>"
or something like this
