### ISSUE TITLE
[BUG]: Change color value

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/QuoteVerse#51]
### Kindly explain, what is the issue or what bug do you want to be fixed?

The color of Added by <Username> is not being seen correctly.
can anyone fix this?
screen shot given below.
you just have to change the link color compatible with all the bg color.

like: if the bg is dark type color, choose text color as light color.

### Screenshot of the issue.

![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/75330767/0f4d6fde-1dc6-48bb-ac8d-ba9b87368219)
![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/75330767/255ceecd-ce46-4526-8b94-892f3ec113e5)
![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/75330767/afff8e68-7044-4ec0-92da-64aff336524d)
![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/75330767/8e5fc62d-5b40-4441-bd02-8fee05ed95d3)

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [x] i am sure, this issue is not raised before.

### Do you want to fix the issue?

None

**Comment by Shariar-Hasan** [comment]
assigned to you.
give a star to the repo,
read otribution guideline

**Comment by alriyadsouza** [comment]
Can I be assigned to this issue if it doesn't get fixed?

**Comment by Shariar-Hasan** [comment]
already assigned to @adit-shriyans
