### ISSUE TITLE
[BUG]: Button position change

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/QuoteVerse#53]
### Kindly explain, what is the issue or what bug do you want to be fixed?

I want anyone to solve this issue.
there is a gap between both the buttons. 
can anyone make the first one attached with the concroller button,
and second one with the first one.
if you do want, get assigned and make a PR

### Screenshot of the issue.

![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/75330767/dbca9062-ade2-4583-8be4-f88e1163f09e)

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] i am sure, this issue is not raised before.

### Do you want to fix the issue?

None

**Comment by vivekmahindrakar** [comment]
hey can you assign this issue to me?

**Comment by Shariar-Hasan** [comment]
@vivekmahindrakar assigned.
do start the repo, 
then make changes,
make a PR

**Comment by Shariar-Hasan** [comment]
This Issue has been close.
i have fixed it
