### ISSUE TITLE
[FEATURE]: Animation Effect on Quote

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/QuoteVerse#56]
### Description

Make a cool animation effect on new quote load,
it could be fade, zoom in or any other animation type.(it must look good)
try not to use any third party package or library.
try out your skill of raw css and js

give a star,
make a PR
get merged 😀

### Screenshots.

![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/75330767/52244be9-a431-4a9a-9f2e-0bdbd39d049c)

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] I checked and didn't find similar issue

### Are you willing to work on this issue ?

None

**Comment by iHassan** [comment]
@Shariar-Hasan can you please assign this to me

**Comment by Shariar-Hasan** [comment]
go for it,
you must star the repo,
make a PR 
get Merged.
and follow the contribution rules
