### ISSUE TITLE
[FEATURE]: Animation on Added by section

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/QuoteVerse#58]
### Description

make an animation such as:  
the added by section will pop up from the back side of the generate quote button.

dont use any thirt party package or library for the animation, 
use your raw css skill to do it.

### Screenshots.

![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/75330767/95644d52-a65d-49fa-b4d1-9dfea03b4331)

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] I checked and didn't find similar issue

### Are you willing to work on this issue ?

None

**Comment by Jenish-Dhanani** [comment]
I would like to do it.
