### ISSUE TITLE
[BUG]: Improve mobile view

### ISSUE THREAD

**Issue by Aaryash-Shakya** [Shariar-Hasan/QuoteVerse#66]
### Kindly explain, what is the issue or what bug do you want to be fixed?

# I want to improve user experience for mobile view.

The main problem I find in mobile view is 

### font size for quote author too small
The font for .quote-author is too small and very difficult to read on mobile view.
> I would like to slightly increase the font by setting a min font size limit.

### Also I think the mobile design can be slightly improved 
For short quote the container doesn't take full viewport height or center itself horizontally
> Either we can align the container to be horizontally centered or make the container take the full mobile viewport height
> For full viewport height, we can set the min height to be 100vh so that it takes full height by default and if the quote is really long, then the container can expand longer than the screen height to fit the long quote

If you assign this task to me then I can fix both or just the font size problem depending on what you want.

### Screenshot of the issue.

![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/100826663/003fb630-0bd9-490f-a2d7-f72cf9ab1f7f)
<br/>
### proposed solutions
on aligning horizontally
![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/100826663/4d24f325-ded6-400a-ba73-23bff1e38a0d)

on taking full height
![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/100826663/bdd96c89-5e3b-4060-b31b-55f422aaa6aa)

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] i am sure, this issue is not raised before.

### Do you want to fix the issue?

Yes, I want to fix it

**Comment by Shariar-Hasan** [comment]
full screen would be good i think.
and in mobile view, make the container non rounded.

![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/75330767/78426202-4b48-4ec0-8cd5-fa9c2f198dc1)

what do you say? 
would it be better?

**Comment by Aaryash-Shakya** [comment]
i think full screen will look good and instead of outer corner being rounded we can round the inner corner
