### ISSUE TITLE
[BUG]: Whatsapp sharing not working

### ISSUE THREAD

**Issue by Jenish-Dhanani** [Shariar-Hasan/QuoteVerse#68]
### Kindly explain, what is the issue or what bug do you want to be fixed?

Greetings,

As I explained in yesterday's bug, Following the integration of the animation code with the quote, there was a modification in the DOM structure of the quote body. Previously, it comprised a single element, whereas now each word is encapsulated within an individual HTML element. Consequently, when selecting the quote text, it no longer selects the quote text. This is a minor issue that I can address. Kindly assign it to me, and I will take care of the fix.

Expected:
On clicking on WhatsApp icon, it should open WhatsApp sharing with the following quote text and author name
"Persistence guarantees that results are inevitable."- Paramahansa Yogananda

Behaving:
Nothing happens when I click on the Whatsapp icon.

Appreciate it,
Jenish

### Screenshot of the issue.

Not a UI issue.

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] i am sure, this issue is not raised before.

### Do you want to fix the issue?

Yes, I want to fix it

**Comment by Shariar-Hasan** [comment]
go for it 💥
