### ISSUE TITLE
[BUG]: Hover effect on Facebook   share button

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/QuoteVerse#71]
### Kindly explain, what is the issue or what bug do you want to be fixed?

After the page is fully loaded,
when ever any user hover on facebook share button.
the button reanimate,
we want any one to remove that reanimation .

make sure to read the contribution rules.

### Screenshot of the issue.

![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/75330767/d2f6e89a-028b-4c9e-b66f-832d91554d72)

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] i am sure, this issue is not raised before.

### Do you want to fix the issue?

None

**Comment by MohitBansal321** [comment]
could you assgin me

**Comment by MohitBansal321** [comment]
yeah sure

**Comment by Shariar-Hasan** [comment]
assigned,
star the repo, and do the work

**Comment by MohitBansal321** [comment]
The error occurred due to adding a new div through the event listener of the Twitter and Facebook icon

**Comment by Shariar-Hasan** [comment]
> The error occurred due to adding a new div through the event listener of the Twitter and Facebook icon

did you understand the problem?

**Comment by MohitBansal321** [comment]
> > The error occurred due to adding a new div through the event listener of the Twitter and Facebook icon
> 
> did you understand the problem?

Whenever I add the inner HTML through this event listener the bug occurs
I comment on this lines inner HTML then its working fine

**Comment by Shariar-Hasan** [comment]
> > > The error occurred due to adding a new div through the event listener of the Twitter and Facebook icon
> > 
> > 
> > did you understand the problem?
> 
> Whenever I add the inner HTML through this event listener the bug occurs I comment on this lines inner HTML then its working fine

exactly,
innerHTML.
but one thing you have to fix is that.
you should not comment code inside code.
either keep it or delete it.

**Comment by Shariar-Hasan** [comment]
Make a PR , if you fix it

**Comment by MohitBansal321** [comment]
> > > > The error occurred due to adding a new div through the event listener of the Twitter and Facebook icon
> > > 
> > > 
> > > Did you understand the problem?
> > 
> > 
> > Whenever I add the inner HTML through this event listener the bug occurs I comment on this lines inner HTML then its working fine
> 
> exactly, innerHTML. but one thing you have to fix is that. you should not comment code inside code. either keep it or delete it.

I mean I just explain you the error so for facebook i added the link directly to element not after the event listener
but for twitter the link is customize so I just need to this in that way i can access customize link

**Comment by Shariar-Hasan** [comment]
but you can fix it by using another event rather than mouse enter.
think about it.

**Comment by MohitBansal321** [comment]
with another event same problem occur

**Comment by Shariar-Hasan** [comment]
> with another event same problem occur

well,
if you use "load", it wont occur.
but you have to fix other thing with it.
can you fix both facebook and twitter?

**Comment by Shariar-Hasan** [comment]
ok, just fix the facebook button,
and make a PR.
i will see the rest
