### ISSUE TITLE
[FEATURE]: INCLUDE a meta tag for link sharing.

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/QuoteVerse#72]
### Description

As we see, QuoteVerse has a share option to various social media platforms.
We want to Include such meta tag , that will help the shared link with some information like: what is Quote Verse,
what service it provides.

### Screenshots.

![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/75330767/15008c9c-bc26-4a55-acd8-008e0b350d37)

For example in whatsapp,  this only showing the link.

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] I checked and didn't find similar issue

### Are you willing to work on this issue ?

None

**Comment by Shivraj-Nakum** [comment]
i would like to contribute on this
plz assign it to me

**Comment by Shariar-Hasan** [comment]
assigned.
but make sure to give a screen shot of the feature you added.
and how its working.

**Comment by Shariar-Hasan** [comment]
hello @Shivraj-Nakum  are you working on it ?

**Comment by Shivraj-Nakum** [comment]
Yes will do pr today
