### ISSUE TITLE
[BUG]: <twitter logo is not visible>

### ISSUE THREAD

**Issue by mohitparmar1** [Shariar-Hasan/QuoteVerse#73]
### Kindly explain, what is the issue or what bug do you want to be fixed?

I want to add different color to twitter logo or we can add new X logo 

### Screenshot of the issue.

![Screenshot (196)](https://github.com/Shariar-Hasan/QuoteVerse/assets/100152343/135292c5-69a0-488f-8902-7571b189cba4)

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] i am sure, this issue is not raised before.

### Do you want to fix the issue?

Yes, I want to fix it

**Comment by shinebhatta** [comment]
Can I please be assigned to this issue?

**Comment by Shariar-Hasan** [comment]
the logo is fine 👍

**Comment by Shariar-Hasan** [comment]
if you have any other issue, create an issue for that
