### ISSUE TITLE
[FEATURE] Add inspirational quotes to Quote.js

### ISSUE THREAD

**Issue by aggarwal-tanushree** [Shariar-Hasan/QuoteVerse#80]
### Description

I would like to contribute inspirational quotes to this Repo under hacktoberfest label.
Kindly assign the issue to me. 
Thanks,
Tanushree A

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] I checked and didn't find similar issue

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Shariar-Hasan** [comment]
no need to open a issue for adding quote.
mentioned in the contribution guideline.
