### ISSUE TITLE
[FEATURE]: <Arrange Quotes Category Options in Alphabetical Order with 'Random'  First>

### ISSUE THREAD

**Issue by sangdeepganvir** [Shariar-Hasan/QuoteVerse#88]
### Description

Enhancement request to alphabetically order quote categories, keeping "random" as the first option for improved user navigation.

### Screenshots.

![quoteverse](https://github.com/Shariar-Hasan/QuoteVerse/assets/41817210/25725a25-bf29-449b-8ea2-f50761b9bc37)

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] I checked and didn't find similar issue

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by sangdeepganvir** [comment]
@shadmehr-salehi  Can you assign this issue to me so that now I can create PR according to the guidelines?

**Comment by Shariar-Hasan** [comment]
You are assigned,
rules are rules,
as there are many pool requests,
we have to maintain conflict while.
thats why we assign particular work to particular person.

**Comment by sangdeepganvir** [comment]
Yes , I understand.
Will be carefull from next time.
