### ISSUE TITLE
[FEATURE]: Add contribution info in Card

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/QuoteVerse#91]
### Description

In the contributors page,
we can make another text, which will refer to how many quotes they have added. 
like "Contributed in 20 Quotes"
well not all of them  added quote fixed bug, added feature,
so they can also have text of "Contributed in BugFix/Feature"

### Screenshots.

![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/75330767/1841f637-ebc6-4439-8b9e-5184bc3d5655)

### Additional information

If Anyone interested in adding this feature.
Get assigned and get merged.

but what is important is [read the contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] I checked and didn't find similar issue

### Are you willing to work on this issue ?

None

**Comment by vihar-s1** [comment]
I would like to work on this issue!

## Idea
I can add the details about how many commits the person has made and other details like the timestamp of the last commit and more.

**Comment by Shariar-Hasan** [comment]
our contributor page has been changed,
go to repository website,
and see the contribtor page, then tell us, can you do it?
if yes, then start working, i will assign you later.

**Comment by vihar-s1** [comment]
Already saw the code and the website. I am asking to be assigned after that only.

**Comment by Shariar-Hasan** [comment]
Go for it.
You are assigned🙂😁

**Comment by vihar-s1** [comment]
thanx
