### ISSUE TITLE
[OTHER] Add new Quotes

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/QuoteVerse#93]
### Description

Try to add new quotes with previous categories.
you dont have to get assigned for adding quotes.
and make sure to [read the contribtion guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md) 

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

### Are you willing to work on this issue ?

None

**Comment by Vishnudas2003** [comment]
Hello @Shariar-Hasan I would like to work on this issue

**Comment by Shariar-Hasan** [comment]
> you dont have to get assign for adding quotes.

**Comment by Kapileswar-Moharana** [comment]
@Shariar-Hasan  Assign This To me under Hacktoberfest

**Comment by Shariar-Hasan** [comment]
> you dont have to get assigned for adding quotes

.

**Comment by Kapileswar-Moharana** [comment]
> > you dont have to get assigned for adding quotes
> 
> .

Why ?

**Comment by Shariar-Hasan** [comment]
> > > you dont have to get assigned for adding quotes
> > 
> > 
> > .
> 
> Why ?

what do you mean by why?
adding quotes does not need to get assigned,
just make a PR.
you should read [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

**Comment by Kapileswar-Moharana** [comment]
> > > > you dont have to get assigned for adding quotes
> > > 
> > > 
> > > .
> > 
> > Why ?
> 
> what do you mean by why?
> adding quotes does not need to get assigned,
> just make a PR.
> you should read [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md) 

@Shariar-Hasan this is the reason that I don't know that's why m asking why ?
Ok then.

**Comment by Shariar-Hasan** [comment]
that why i told you to read the contribution guideline.

**Comment by Kapileswar-Moharana** [comment]
@Shariar-Hasan Check It Sir #125

**Comment by Shariar-Hasan** [comment]
> @Shariar-Hasan Check It Sir #125

do not mention any PR for Quote.

**Comment by Kapileswar-Moharana** [comment]
> > @Shariar-Hasan Check It Sir #125
> 
> do not mention any PR for Quote.

@Shariar-Hasan But After this Merged it is not reflecting in Hacktoberfest ?

**Comment by Shariar-Hasan** [comment]
> > > @Shariar-Hasan Check It Sir #125
> > 
> > 
> > do not mention any PR for Quote.
> 
> @Shariar-Hasan But After this Merged it is not reflecting in Hacktoberfest ?

no problem,
as long as the repo has a topic : hacktoberfest,
your PR will still be count for it.
and, i am just asking not to mention issue in PR **Only for Quote add**
