### ISSUE TITLE
[FEATURE]: Contributors page UI need more cool looking design 

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/QuoteVerse#94]
### Description

if you have a idea of more good looking desing than tha, you can get a screen shot of your idea in the comment,
if it is good enough, we will assign you for the contribbution.
make sure to [read the contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

### Screenshots.

![image](https://github.com/Shariar-Hasan/QuoteVerse/assets/75330767/417ec8dd-e3aa-44a3-99ff-751e23801f79)

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] I checked and didn't find similar issue

### Are you willing to work on this issue ?

None

**Comment by Muhammad-Shahid-Jamal** [comment]
![contibutors_screen](https://github.com/Shariar-Hasan/QuoteVerse/assets/26340344/1fbf71c3-675d-43bc-b0ad-4e47561cd9e0)

# what about that design?

**Comment by Muhammad-Shahid-Jamal** [comment]
@Shariar-Hasan

**Comment by Shariar-Hasan** [comment]
cool,
go for it .
assigned
