### ISSUE TITLE
[FEATURE]: Hover effect for see all contributors button and the click to contribute button

### ISSUE THREAD

**Issue by KiranPolaki** [Shariar-Hasan/QuoteVerse#98]
### Description

In the main page adding the Hover effect for the {See all Contributors} button would look good and help maintain consistency over the enter web page and same for {Click to contribute} button.

### Screenshots.

![Screenshot 2023-10-21 231312](https://github.com/Shariar-Hasan/QuoteVerse/assets/121670156/a1689d16-5c2a-446e-a784-81e8131df363)

### Code of Conduct

- [X] i have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)
- [X] I checked and didn't find similar issue

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Shariar-Hasan** [comment]
assiigned,
try to make it better,
best of luck
